#!/usr/bin/env bash
# Cleanup script: deletes duplicate proposal files from pending/ that also exist in approved/.
# Generated by Cowork scheduled task on 2026-05-19. Review _duplicate_pending_to_delete.txt
# before running. Run from this directory or pass the proposals dir as $1.

set -euo pipefail
DIR="${1:-/Users/tomloughran/Documents/Claude/Projects/RC Karpathy Wiki Project/wiki/inbox/proposals}"
cd "$DIR"

LIST="$DIR/_duplicate_pending_to_delete.txt"
if [ ! -f "$LIST" ]; then
  echo "Missing $LIST" >&2; exit 1
fi

count=0
while IFS= read -r fname; do
  [ -z "$fname" ] && continue
  if [ -f "approved/$fname" ] && [ -f "pending/$fname" ]; then
    rm -v "pending/$fname"
    count=$((count + 1))
  else
    echo "SKIP (not a true duplicate any more): $fname"
  fi
done < "$LIST"

echo "Deleted $count file(s) from pending/."
