'use strict';

// c2a2-search.js
// Shared C2A2 search-pipeline module. Holds the Pathway-00 broker URL,
// device-id handling, the raw broker fetch with error-code translation,
// and the web-cap / Tavily-down one-shot fallback that the Community
// Explorer first shipped on 2026-05-28 (commit 479910d). Every C2A2
// surface (Community Explorer, Sociogram, future Accelerator tabs)
// imports this same module so behavior, banners, and caps stay aligned.
//
// Single source of truth: edit this file. The Sociogram (wiki_narration.html)
// is regenerated by generate_visualization.py, which INLINES the contents
// of this file into the self-contained HTML. Do not duplicate the code
// in the Python template.
//
// API (attached to window.C2A2Search):
//   - BROKER_URL              constant
//   - getDeviceId()           -> stable per-browser UUID (localStorage)
//   - callBroker({action,system,user,model})
//                              -> Promise<payload>; throws Error whose
//                              .message is one of:
//                              'web-free-limit' | 'free-limit' |
//                              'rate-limited'  | 'search-provider-down' |
//                              'broker-http-N'
//   - enrich({useWeb, dataset:{system,user,model?},
//             web:{system,user,model?}?})
//                              -> Promise<{payload, mode, transport, warning}>
//                              On useWeb=true: tries 'web_enrich'; on
//                              'web-free-limit' or 'search-provider-down'
//                              falls back ONCE to 'enrich' with the
//                              dataset prompts and attaches a banner.

(function () {
  const BROKER_URL = 'https://akhcocmgfwybdovqeovd.supabase.co/functions/v1/cc-broker';
  const DEVICE_ID_KEY = 'c2a2_device_id';
  const REQUEST_TIMEOUT_MS = 20000;

  const getDeviceId = () => {
    try {
      let id = (localStorage.getItem(DEVICE_ID_KEY) || '').trim();
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
        id = (window.crypto && typeof crypto.randomUUID === 'function')
          ? crypto.randomUUID()
          : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
              const r = (Math.random() * 16) | 0;
              return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
            });
        localStorage.setItem(DEVICE_ID_KEY, id);
      }
      return id;
    } catch (e) {
      return '00000000-0000-4000-8000-000000000000';
    }
  };

  const callBroker = async (opts) => {
    const action = (opts && opts.action) || 'enrich';
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const resp = await fetch(BROKER_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CC-Device': getDeviceId(),
        },
        body: JSON.stringify({
          action: action,
          system: opts.system,
          user: opts.user,
          model: opts.model,
        }),
        signal: controller.signal,
      });
      let body = null;
      try { body = await resp.json(); } catch (e) { body = null; }
      if (resp.status === 402) {
        const code = body && body.error === 'web_free_limit_reached' ? 'web-free-limit' : 'free-limit';
        const err = new Error(code); err.body = body; throw err;
      }
      if (resp.status === 429) {
        const err = new Error('rate-limited'); err.body = body; throw err;
      }
      if (resp.status === 502 && body && body.error === 'search_provider_down') {
        const err = new Error('search-provider-down'); err.body = body; throw err;
      }
      if (!resp.ok) {
        const err = new Error('broker-http-' + resp.status); err.body = body; throw err;
      }
      return body || {};
    } finally {
      clearTimeout(timer);
    }
  };

  // enrich() runs one broker call and, when web search is the active branch
  // and the broker returns the cap-hit / provider-down sentinels, falls back
  // ONCE to the dataset branch with a user-facing banner. Caller supplies
  // both prompt pairs because system+user strings vary per consumer (the
  // Community Explorer pins the answer to dataset candidates; the Sociogram
  // pins it to visible vault nodes).
  const enrich = async ({ useWeb, dataset, web }) => {
    if (!dataset || typeof dataset.system !== 'string' || typeof dataset.user !== 'string') {
      throw new Error('c2a2-search.enrich: dataset {system,user} required');
    }
    if (useWeb && (!web || typeof web.system !== 'string' || typeof web.user !== 'string')) {
      throw new Error('c2a2-search.enrich: web {system,user} required when useWeb=true');
    }

    if (useWeb) {
      try {
        const payload = await callBroker({
          action: 'web_enrich',
          system: web.system,
          user: web.user,
          model: web.model,
        });
        return {
          payload: payload,
          mode: 'database-plus-web-cited',
          transport: 'web-enriched',
          warning: '',
        };
      } catch (err) {
        if (err.message !== 'web-free-limit' && err.message !== 'search-provider-down') {
          throw err;
        }
        const banner = err.message === 'web-free-limit'
          ? 'External search cap reached today -- showing in-dataset results.'
          : 'External search unavailable -- showing in-dataset results.';
        const fallbackPayload = await callBroker({
          action: 'enrich',
          system: dataset.system,
          user: dataset.user,
          model: dataset.model,
        });
        return {
          payload: fallbackPayload,
          mode: err.message === 'search-provider-down'
            ? 'external-search-unavailable'
            : 'database-only-after-cap',
          transport: 'openai-enriched',
          warning: banner,
        };
      }
    }

    const payload = await callBroker({
      action: 'enrich',
      system: dataset.system,
      user: dataset.user,
      model: dataset.model,
    });
    return {
      payload: payload,
      mode: 'openai-enriched',
      transport: 'openai-enriched',
      warning: '',
    };
  };

  window.C2A2Search = {
    BROKER_URL: BROKER_URL,
    getDeviceId: getDeviceId,
    callBroker: callBroker,
    enrich: enrich,
  };
})();
