#!/usr/bin/env python3
"""Prepend an honest provenance notice to every LLM-generated assumption/presumption
stress-test file under wiki/architecture/lit_search_results/.

These files were generated by the 15a/15b agents WITHOUT any database-backed
retrieval; their citations are model-generated and some are inaccurate or
fabricated. This banner makes that provenance visible in the file itself so the
corpus is never mistaken for verified literature search.

Idempotent: re-running skips files that already carry the notice.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent / "wiki" / "architecture" / "lit_search_results"
MARKER = "Provenance notice."
BANNER = (
    "> ⚠️ **Provenance notice.** This file was generated by an LLM agent "
    "(15a/15b) as\n"
    "> *adversarial assumption-stress-testing*, not a database-backed literature "
    "search.\n"
    "> Citations are model-generated and **have not been verified against any source\n"
    "> (Crossref, Semantic Scholar, etc.); some are inaccurate or fabricated.** Treat "
    "the\n"
    "> *arguments* as hypothesis-generation; do not cite the *references* without\n"
    "> independent verification.\n\n"
)


def main() -> None:
    if not ROOT.is_dir():
        raise SystemExit(f"Not found: {ROOT}")
    files = sorted(ROOT.rglob("*.md"))
    modified = skipped = 0
    for f in files:
        text = f.read_text(encoding="utf-8")
        if MARKER in text[:600]:
            skipped += 1
            continue
        f.write_text(BANNER + text, encoding="utf-8")
        modified += 1
    print(f"files={len(files)} modified={modified} skipped={skipped}")


if __name__ == "__main__":
    main()
